name: Test Rust

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    name: Paths filter
    runs-on: ubuntu-22.04
    outputs:
      should_run: ${{ steps.filter.outputs.src }}
    steps:
      - uses: actions/checkout@v4

      - uses: AurorNZ/paths-filter@v3
        id: filter
        with:
          filters: |
            src:
              - '!web/package.json'
              - '!web/package-lock.json'
              - '!web/packages/**'
              - '!**/*.md'

  build:
    needs: changes
    if: needs.changes.outputs.should_run== 'true'
    name: Test Rust ${{ matrix.rust_version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.rust_version == 'nightly' || matrix.rust_version == 'beta' }}
    strategy:
      fail-fast: false
      matrix:
        rust_version: [stable]
        os: [ubuntu-22.04, windows-latest, macos-latest]
        include:
          - rust_version: nightly
            os: ubuntu-22.04
          - rust_version: beta
            os: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust_version }}
          components: rustfmt, clippy

      - name: Cache Cargo output
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "desktop"
          save-if: ${{ github.ref == 'refs/heads/master' }}

      - name: Install cargo nextest
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-nextest

      - name: Run tests with image tests
        if: runner.os == 'macOS'
        # TODO: Disallow retries in general once we can allow only after SIGABRT.
        # See: https://github.com/nextest-rs/nextest/issues/1172
        run: cargo nextest run --workspace --locked --no-fail-fast --retries 2 -j 4 --features imgtests,lzma,jpegxr
        env:
          XDG_RUNTIME_DIR: '' # dummy value, just to silence warnings about it missing

  check-required:
    needs: changes
    if: needs.changes.outputs.should_run == 'false'
    name: Test Rust ${{ matrix.rust_version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust_version: [stable]
        os: [ubuntu-22.04, windows-latest, macos-latest]
        include:
          - rust_version: nightly
            os: ubuntu-22.04
          - rust_version: beta
            os: ubuntu-22.04

    steps:
      - name: No-op
        run: echo noop
